# Generated by Django 4.2.5 on 2023-11-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genrefilmwork',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personfilmwork',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(
                choices=[('movie', 'movie'), ('tv_show', 'tv_show')], default='movie', verbose_name='type'
            ),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, unique=True, verbose_name='description'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date'], name='film_work_creation_date_idx'),
        ),
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['film_work', 'genre'], name='film_work_genre_idx'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['film_work', 'person', 'role'], name='film_work_person_role_idx'),
        ),
        migrations.AlterModelTable(
            name='filmwork',
            table="content'.'film_work",
        ),
        migrations.AlterModelTable(
            name='genre',
            table="content'.'genre",
        ),
        migrations.AlterModelTable(
            name='genrefilmwork',
            table="content'.'genre_film_work",
        ),
        migrations.AlterModelTable(
            name='person',
            table="content'.'person",
        ),
        migrations.AlterModelTable(
            name='personfilmwork',
            table="content'.'person_film_work",
        ),
    ]
