# Generated by Django 4.2.5 on 2023-10-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_certificate_filmwork_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='file_path',
            new_name='sandwich',
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('tv_show', 'tv_show')], default='movie', verbose_name='type'),
        ),
    ]
